" Vimrc
"
" Shamelessly borrowed from https://github.com/christoomey/dotfiles/blob/master/vim/vimrc.
"
" I was looking for a way to better organize my plugins and their settings and wanted to 'modularize' my
" vimrc configuration. I happened to look at Chris's vimrc in his dotfiles and it was EXACTLY what I was
" envisioning.
"
" The only addition I'm going to look to make is to look for allowing the specification of dependencies.
" Not full-blown dependency management--juts along the lines of 'this plugin requries these other plugins'.
" I'm not going to go crazy with tracking 'plugin version' dependencies. And this should only be needed in the
" case where its requried in order to set settings where plugin load ordering is important.
"
" This file contains the minimal settings to set the foundation, with the majority of the configuration
" settings living in f iles spread between .vim/rcfiles and .vim/rcplugins.

set nocompatible

" Need to set the leader before defining any leader mappings
"let mapleader = "\<Space>"

" Automatic installation of vim-plug if not found
let data_dir = has('nvim') ? stdpath('data') . '/site' : "$HOME/.vim"
if empty(glob(data_dir . '/autoload/plug.vim'))
    silent execute '!curl -fLo '.data_dir.'/autoload/plugin.vim --create-dirs https://raw.githubusercontent.junegunn/vim-plug/master/plug.vim'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

let s:autoinstall_missing_plugins = 0
if (s:autoinstall_missing_plugins)
    " Automatically install missing plugins. NOTE: This may increase vim startup time.
    autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
                \ | PlugInstall --sync
                \ | source $MYVIMRC
                \ | endif
endif

augroup filetype_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END

" Detect if we're running in a WSL environment and return 1 or 0
function! IsWSL()
    if has('unix')
        let lines = readfile('/proc/version')
        if lines[0] =~ 'microsoft-standard-WSL2'
            return 1
        endif
    endif

    return 0
endfunction

" Get all configuration files in the specified directory under $HOME/.vim
"   Use '/a/directory/config.vim' to source a specific configuration file.
"   Use '/a/directory/*.vim' to get all *.vim files in /a/directory.
"   Use '/a/directory/*' to get all configuration files in the directory /a/directory.
"   Use '/a/directory/**' to get all configuration files in the directory /a/directory and any of its
"     sub-directories.
function! s:SourceConfigFilesIn(configFiles)
    if a:configFiles !~? '\v\*(|\*|\..+)?'
        let config_file = '$HOME/.vim/' . a:configFiles
        execute 'source' config_file
    else
        let config_files  = '$HOME/.vim/' . a:configFiles
        for config_file in split(glob(config_files), '\n')
            if filereadable(config_file)
                execute 'source' config_file
            endif
        endfor
    endif
endfunction

" Force shell to /bin/bash to avoid E484 can't find tmp files in /var/folders/*
set shell=/bin/bash

" This can be used to 'conditionally load' plugins so that :PlugClean will work properly
function! LoadOn(cond, ...)
    let opts = get(a:000, 0, {})
    return a:cond ? opts : extend(opts, { 'on': [], 'for': [] })
endfunction

iabbrev servcie service

call plug#begin()
call s:SourceConfigFilesIn('rcplugins/colorschemes.vim')
" TODO: Figure out a way to declaratively specify 'load order'.
call s:SourceConfigFilesIn('rcplugins/polyglot.vim')
call s:SourceConfigFilesIn('rcplugins/formatting/*')
call s:SourceConfigFilesIn('rcplugins/lang/*')
call s:SourceConfigFilesIn('rcplugins/scm.vim')
call s:SourceConfigFilesIn('rcplugins/ide.vim')
call s:SourceConfigFilesIn('rcplugins/tmux.vim')
call s:SourceConfigFilesIn('rcplugins/qol.vim')

Plug 'tpope/vim-dadbod'
Plug 'vim-test/vim-test'

" Per https://github.com/ryanoasis/vim-devicons, ALWAYS load this as the VERY LAST plugin.
Plug 'ryanoasis/vim-devicons', { 'branch': 'origin/pr/446' }
let g:WebDevIconsUnicodeByteOrderMarkerDefaultSymbol = ''
" let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}
" let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['pn'] = nr2char(0xF0096)
call plug#end()
"let &rtp='~/.vim/plugged/potion,'.&rtp
" note: don't need to set this. per help documentation, as soon as a user .vimrc
" file is found, this is already set! this is not true when the system .vimrc
" file is used, however.
"set nocompatible

" if there's a .vimrc file in the directory in which vim is opened, source it.
set exrc
set showmode
set cmdheight=1
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8
" Set the cursor -- TODO: Lookup more info on this
set guicursor=
set backspace=indent,eol,start
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent smartindent shiftround smarttab
set foldcolumn=5
set textwidth=0
" TODO: Perhaps make an autocmd for this so the column is only visible while in INSERT mode...
"set colorcolumn=110
set wrapmargin=2
set relativenumber
set number
set signcolumn=yes
set confirm " confirm destructive operations made on non-saved buffers
set hidden
set lazyredraw
set noerrorbells
set path+=.,./**
set title
set wildmenu
set wildmode=list:longest,list:full
set hlsearch
set incsearch
" start scrolling the screen when the cursor reaches 'n' lines from the top/bottom
set scrolloff=8
" When :splitting a window, put the new window below the current window
set splitbelow
" When :vsplitting a window, put the new window to the right of the current window
set splitright
" Set completion mode options (think, intellisense menu)
" My options are:
"  - menuone: Show a menu even for a single match
"  - longest: Only insert the longest common text of the matches. Use <C-L> to enter more text when the
"             popup is shown.
"  - noinsert: Do not insert any text until a selection is actually made
"  - noselect: Do not 'auto-select' a match--user has to explicitly select
"set completeopt=menuone,noinsert,noselect
if (has('patch-8.1.1880'))
    set completeopt=longest,menuone,popuphidden
    set completepopup=highlight:Pmenu,border:off
else
    set completeopt=longest,menuone,preview
    set previewheight = 5
endif
" Enable snippet completion, using the ultisnips plugin
let g:OmniSharp_want_snippet = 1

augroup omnisharp_commands
    autocmd!

    " Show type information automitacally when the cursor stops moving.
    " Note that the type is echoed to the Vim command line, and will overwrite
    " any other messages in this space, including e.g. ALE linting messages.
    autocmd CursorHold *.cs OmniSharpTypeLookup

    " The following commands are contextual, based on the cursor position
    autocmd FileType cs nmap <silent> <buffer> gd <Plug>(omnisharp_go_to_definition)
    autocmd FileType cs nmap <silent> <buffer> <Leader>osfu <Plug>(omnisharp_find_usages)
    autocmd FileType cs nmap <silent> <buffer> <Leader>osfi <Plug>(omnisharp_find_implementations)
    autocmd FileType cs nmap <silent> <buffer> <Leader>ospd <Plug>(omnisharp_preview_definition)
    autocmd FileType cs nmap <silent> <buffer> <Leader>ospi <Plug>(omnisharp_preview_implemenattions)
    autocmd FileType cs nmap <silent> <buffer> <Leader>ost <Plug>(omnisharp_type_lookup)
    autocmd FileType cs nmap <silent> <buffer> <Leader>osd <Plug>(omnishrap_documentation)
    autocmd FileType cs nmap <silent> <buffer> <Leader>osfs <Plug>(omnisharp_find_symbol)
    autocmd FileType cs nmap <silent> <buffer> <Leader>osfx <Plug>(omnisharp_fix_usings)
    autocmd FileType cs nmap <silent> <buffer> <C-\> <Plug>(omnisharp_signature_help)
    autocmd FileType cs imap <silent> <buffer> <C-\> <Plug>(omnisharp_signature_help)

    " Navigate up and down by method/property/field
    autocmd FileType cs nmap <silent> <buffer> [[ <Plug>(omnisharp_navigate_up)
    autocmd FileType cs nmap <silent> <buffer> ]] <Plug>(omnisharp_navigate_down)
    " Find all code errors/warnings for the current solution and populate the quickfix window
    autocmd FileType cs nmap <silent> <buffer> <Leader>osgcc <Plug>(omnisharp_global_code_check)
    " Contextual code actions (uses fzf, vim-clap, CtrlP or unite.vim selector when available)
    autocmd FileType cs nmap <silent> <buffer> <Leader>osca <Plug>(omnisharp_code_actions)
    autocmd FileType cs xmap <silent> <buffer> <Leader>osca <Plug>(omnisharp_code_actions)
    " Repeat the last code action performed (does not use a selector)
    autocmd FileType cs nmap <silent> <buffer> <Leader>os. <Plug>(omnisharp_code_action_repeat)
    autocmd FileType cs xmap <silent> <buffer> <Leader>os. <Plug>(omnisharp_code_action_repeat)

    autocmd FileType cs nmap <silent> <buffer> <Leader>os= <Plug>(omnisharp_code_format)

    autocmd FileType cs nmap <silent> <buffer> <Leader>osnm <Plug>(omnisharp_rename)

    autocmd FileType cs nmap <silent> <buffer> <Leader>osre <Plug>(omnisharp_restart_server)
    autocmd FileType cs nmap <silent> <buffer> <Leader>osst <Plug>(omnisharp_start_server)
    autocmd FileType cs nmap <silent> <buffer> <Leader>ossp <Plug>(omnisharp_stop_server)
augroup END

" Set update time.
" The default is 4s!! Reduce it to at least 100ms
set updatetime=100
" Avoid some 'hit-enter' prompts
set shortmess=filmnrxoOc
" Start diff mode using vertical splits, in addition to the default values
set diffopt+=vertical

" Change the characters that are used for showing whitespace
set listchars="tab:\uF811\uF811,trail:\uB7,nbsp:\u2420,lead:\uB7,space:\uB7,precedes:\u2026,extends:\u2026"


let $RTP=split(&runtimepath, ',')[0]

if (has("termguicolors"))
    set termguicolors
elseif (!has('gui_running'))
    set t_Co=256
endif

if (has('nvim'))
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif

filetype plugin indent on " Indentation rules follow those of plug-ins, then file types.
syntax enable
set background=dark
"colorscheme spaceduck
colorscheme base16-classic-dark

" Improve support for mouse use with mintty
set mouse=a
if has("mouse_sgr")
    set ttymouse=sgr
else
    set ttymouse=xterm2
end

" Override git-for-windows setting clipboard=unnamed causing
" the system clipboard to clobber the default unnamed register
if has("clipboard")
    set clipboard=
endif

" if (has('unnamedplus'))
"     set clipboard=unnamed,unnamedplus
" endif

" Only show line highlighting when in INSERT mode.
augroup fourpastmidnight_vimrc
    autocmd!
    autocmd User * call AirlineInit()
    autocmd BufEnter * setlocal cursorline
    autocmd BufEnter * setlocal colorcolumn=110
    autocmd BufLeave * setlocal nocursorline
    autocmd BufLeave * setlocal colorcolumn=0
    autocmd BufRead,BufNewFile *.[jt]sx? setlocal conceallevel=1
    autocmd BufRead,BufNewFile *.{md,mdx,mdown,mkd,mkdn,markdown,mdwn} setlocal conceallevel=2
    autocmd FileType gitcommit let b:EditorConfig_disable = 1
    autocmd FileType html,css,markdown,sass,scss EmmetInstall
    autocmd FileType javascript setlocal foldmethod=syntax
    autocmd FileType javascript setlocal foldmethod=syntax
    autocmd FileType javascriptreact setlocal foldmethod=syntax
    autocmd FileType scss setlocal iskeyword+=-
    autocmd FileType typescript setlocal foldmethod=syntax
    autocmd FileType typescriptreact setlocal foldmethod=syntax
augroup END

set secure
