" NOTE: Don't need to set this. Per help documentation, as soon as a user .vimrc
" file is found, this is already set! This is NOT true when the system .vimrc
" file is used, however.
"set nocompatible

" If there's a .vimrc file in the directory in which Vim is opened, source it.
set exrc
set hidden
set backspace=indent,eol,start
set encoding=utf-8
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent smartindent
set textwidth=0
set path+=**
set wildmenu
" Set update time.
" The default is 4s!! Reduce it to at least 100ms
set updatetime=100
" Avoid some 'hit-enter' prompts
set shortmess=filmnrxoOc

let $RTP=split(&runtimepath, ',')[0]

if (has("termguicolors"))
    set termguicolors
endif

filetype plugin on
syntax enable

let data_dir = has('nvim') ? stdpath('data') . '/site' : "$HOME/vimfiles"
if empty(glob(data_dir . '/autoload/plug.vim'))
    silent execute '!curl -fLo '.data_dir.'/autoload/plugin.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
endif

if has('wsl')
    let g:is_wsl = 1
elseif exists('$WSL_DISTRO_NAME')
    let g:is_wsl = 1
elseif filereadable('/proc/sys/kernel/osrelease')
            \ && join(readfile('/proc/sys/kernel/osrelease')) =~? 'microsoft\|wsl'
    let g:is_wsl = 1
else
    let g:is_wsl = 0
endif

function! LoadIfExists(relpath)
    let base = fnamemodify($MYVIMRC, ':p:h')
    let full = fnamemodify(base . '/' . a:relpath, ':p')
    if filereadable(full)
        try
            execute 'source' full
            if &verbose >= 9 || (exists('v:verbose') && v:verbose >= 9)
                echom "LoadIfExists: Loaded " . full
            endif
        catch /.*/
            if &verbose >= 12 || (exists('v:verbose') && v:verbose >= 12)
                echohl ErrorMsg
                echom "LoadIfExists: Error sourcing " . full
                echohl None
            endif
        endtry
    else
        if &verbose >= 9 || (exists('v:verbose') && v:verbose >= 9)
            echohl WarningMsg
            echom "LoadIfExists: File not found: " . full
            echohl None
        endif
    endif
endfunction

" Global vim configuration settings to be applied. Some of these may be
" overridden by settings in loaded "modules".

" Override git-for-windows setting clipboard=unnamed causing
" the system clipboard to clobber the default unnamed register
set clipboard=

" Import Plugin Declarations/Registrations
" ========================================================================

" Configure the vim environment first
call LoadIfExists('config/env/wsl.vim')

" Make sure that this file gets loaded before plugin.vim so that unwanted
" parts of vim-polyglot can be disabled upon plugin initilaization!
call LoadIfExists('config/polyglot.vim')

" Load/register all plugins
call LoadIfExists('config/plugins.vim')

" Set the colorscheme and any visual ui aspects related to the chosen
" colorscheme
call LoadIfExists('config/colorscheme.vim')

" Configure all other vim ui aspects.
call LoadIfExists('config/ui.vim')

" Setup IDE-like features for Vim
call LoadIfExists('config/ide/lsp.vim')
call LoadIfExists('config/ide/completion.vim')
call LoadIfExists('config/ide/diagnostics.vim')
call LoadIfExists('config/ide/vimspector.vim')
call LoadIfExists('config/git.vim')

" Configure specific filetype plugin settings
call LoadIfExists('config/filetypes/javascript.vim')
call LoadIfExists('config/filetypes/javascriptreact.vim')
call LoadIfExists('config/filetypes/markdown.vim')
call LoadIfExists('config/filetypes/typescript.vim')
call LoadIfExists('config/filetypes/typescriptreact.vim')

" Configure other plugins that don't fit any category above.
call LoadIfExists('config/plugins/emmet.vim')
call LoadIfExists('config/plugins/rainbow.vim')

" If you have any other autocmds you wish to steup, then this file should ALWAYS be loaded last.
call LoadIfExists('config/autocmmands.vim')

" Only show line highlighting when in INSERT mode.
augroup fourpastmidnight_vimrc
    autocmd!
    " Make doc comments actually look like comments (for PowerShell)
    autocmd ColorScheme * highlight! link poshDocBlockComment Comment
    autocmd ColorScheme * highlight! link poshBlockComment    Comment
    " Ensure folded regions don't override dockblock color
    autocmd ColorScheme * highlight! link Folded Comment
    " Only CBH keywords should be "Special"
    autocmd ColorScheme * highlight! link poshDocBlockKeyword SpecialComment
augroup END
