" Vimrc
"
" Shamelessly borrowed from https://github.com/christoomey/dotfiles/blob/master/vim/vimrc.
"
" I was looking for a way to better organize my plugins and their settings and wanted to 'modularize' my
" vimrc configuration. I happened to look at Chris's vimrc in his dotfiles and it was EXACTLY what I was
" envisioning.
"
" The only addition I'm going to look to make is to look for allowing the specification of dependencies.
" Not full-blown dependency management--juts along the lines of 'this plugin requries these other plugins'.
" I'm not going to go crazy with tracking 'plugin version' dependencies. And this should only be needed in the
" case where its requried in order to set settings where plugin load ordering is important.
"
" This file contains the minimal settings to set the foundation, with the majority of the configuration
" settings living in f iles spread between .vim/rcfiles and .vim/rcplugins.

set nocompatible

" Need to set the leader before defining any leader mappings
"let mapleader = "\<Space>"

" Automatic installation of vim-plug if not found
let data_dir = has('nvim') ? stdpath('data') . '/site' : "$HOME/.vim"
if empty(glob(data_dir . '/autoload/plug.vim'))
    silent execute '!curl -fLo '.data_dir.'/autoload/plugin.vim --create-dirs https://raw.githubusercontent.junegunn/vim-plug/master/plug.vim'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

let s:autoinstall_missing_plugins = 0
if (s:autoinstall_missing_plugins)
    " Automatically install missing plugins. NOTE: This may increase vim startup time.
    autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
                \ | PlugInstall --sync
                \ | source $MYVIMRC
                \ | endif
endif

augroup filetype_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END

" Detect if we're running in a WSL environment and return 1 or 0
function! IsWSL()
    if has('unix')
        let lines = readfile('/proc/version')
        if lines[0] =~ 'microsoft-standard-WSL2'
            return 1
        endif
    endif

    return 0
endfunction

" Get all configuration files in the specified directory under $HOME/.vim
"   Use '/a/directory/config.vim' to source a specific configuration file.
"   Use '/a/directory/*' to get all configuration files in the directory /a/directory.
"   Use '/a/directory/**' to get all configuration files in the directory /a/directory and any of its
"     sub-directories.
function! s:SourceConfigFilesIn(configFiles)
    if a:configFiles =~? '\v\*(|\*|\..+)?'
        execute 'source' a:configFiles
    else
        let config_files  = '$HOME/.vim/' . a:configFiles
        for config_file in split(glob(directory_spalt), '\n')
            if filereadable(config_file)
                execute 'source' config_file
            endif
        endfor
    endif
endfunction

" Force shell to /bin/bash to avoid E484 can't find tmp files in /var/folders/*
set shell=/bin/bash

" This can be used to 'conditionally load' plugins so that :PlugClean will work properly
function! LoadOn(cond, ...)
    let opts = get(a:000, 0, {})
    return a:cond ? opts : extend(opts, { 'on': [], 'for': [] })
endfunction

iabbrev servcie service

call plug#begin()
call s:SourceConfigFilesIn('rcplugins/colorschemes.vim')
" TODO: Figure out a way to declaratively specify 'load order'.
call s:SourceConfigFilesIn('rcplugins/ployglot.vim')
call s:SourceConfigFilesIn('rcplugins/lang/*.vim')


" Utility Plugs

" Going to try vim-signify and see if that works faster/is better.
"Plug 'airblade/vim-gitgutter'
"if has('win32') || has('unixwin32')
"    let g:gitgutter_git_executable = '/c/Program\ Files/Git/bin/git.exe'
"elseif has('unix')
"    let g:gitgutter_git_executable = '/usr/bin/git'
"endif

Plug 'easymotion/vim-easymotion'
Plug 'edkolev/tmuxline.vim'
Plug 'editorconfig/editorconfig-vim'
let g:EditorConfig_exclude_patterns = [ 'fugitive://.*', 'scp://.*' ]
" To disable editorconfig for a filetype, for example:
" au FileType gitcommit let b:EditorConfig_disable = 1

"Plug 'fsharp/vim-fsharp', { 'for': 'fsharp' }
Plug 'godlygeek/tabular'
Plug 'heavenshell/vim-jsdoc', { 'for': ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx' ], 'do': 'make clean && make install' }

Plug 'iberianpig/tig-explorer.vim'

" This doesn't seem to play nice with Coc, so leaving this commented out for now.
"Plug 'ionide/Ionide-vim', { 'do': 'powershell -ExecutionPolicy Unrestricted .\\install.ps1', 'for': 'fsharp' }

Plug 'Jorengarenar/vim-SQL-UPPER'
" Configure vim-SQL-UPPER plugin
let g:SQL_UPPER = 5

Plug 'lifepillar/vim-colortemplate'
Plug 'luochen1990/rainbow'
" interface to be used in order listed
" * `guis`: a list of `gui` (`:h highlight-gui`), used in order listed
" * `ctermfgs`: a list of `ctermfg` (`:h highlight-ctermfg`)
" * `cterms`: a list of `cterm` (`:h highlight-cterm`)
" * `operators`: describe the operators you want to highlight. (NOTE: be
" careful about special characters which need escaping; you can find more
" examples [here](https://github.com/luochen/1990/rainbow/issues3), and you
" can also read the [vim help about
" syn-pattern](https://vimdoc.sourceforge.net/htmldoct/syntax.html#.syn-pattern).
" Note that this option will be overwritten by the `step` part of
" `parentheses`.
" * `paretheses`: A list of parentheses definitions. A paretheses definition
" contains parts like `start=/(/`, `step=/,/`, `stop=/)/`, `fold`,
" `contained`,     `containedin=someSynNames`, `contains=@Spell`. See `:h syntax`
" for more details. Note that the `step` part is defined by this plugin and so
" it is not described by the official vim documentation.
" * `parentheses_options`: options shared between different paretheses; things
" like `containedin=xxxFuncBody`, `contains=@Spell` (or `contains=@NoSpell`)
" ofter appear here. This option is often used to resolve 3rd-party plugin
" compatibility issues.
" * `separately`: Configure for specific filetypes. For filetypes without
" separate configuration, value `0` means disable rainbow color only for this
" type of file. `default` means keep the default shim for this filetype.
" * `syn_name_prefix`: Add a prefix to the name of the syntax definition. This
" option is used to resolve 3rd-party plugin compatibility issues.
" * `after`: Execute some vim commands after the rainbow syntax definition.
" Used to resolve 3rd-party plugin compatibility issues.
" * Keep a field empty to use the default setting.
"
" For more advanced configuration samples, try searching with this tag:
" http://github.com/luochen1990/rainbow/issues?utf8=y&q=label%3A"config+reference"+.
let g:rainbow_active = 1
let g:rainbow_conf = {
\    'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick'],
\    'ctermfgs': ['lightblue', 'lightyellow', 'lightcyan', 'lightmagenta'],
\    'guis': [''],
\    'cterms': [''],
\    'operators': '_,_',
\    'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold'],
\    'separately': {
\         '*': {},
\         'haskell': {
\             'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/\v\{\ze[^-]/ end=/}/ fold']
\         },
\         'lisp': {
\             'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick', 'darkorchid3']
\         },
\         'markdown': {
\             'parentheses_options': 'containedin-markdownCode contained'
\         },
\         'perl': {
\             'syn_name_prefix': 'perlBlockFoldRainbow'
\         },
\         'powershell': {
\             'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/\{/ end=/\}/ fold']
\         },
\         'stylus': {
\             'parentheses': ['start=/{/ end=/}/ fold contains=@colorableGroup']
\         },
\         'typescript': {
\             'parentheses': ['start=/{/ end=/}// fold contains=@colorableGroup', 'start=/(/ end=/)/', 'start=/\[/ end=l\]/']
\         },
\         'vim': {
\             'parentheses_options': 'containedin=vimFuncBody'
\         }
\    }
\}

Plug 'MattesGroeger/vim-bookmarks'
Plug 'mattn/emmet-vim'
" Configuration options for mattn/emmet-vim:
"let g:user_emmet_mode='n'   " Only enable normal mode functions
"let g:user_emmet_mode='inv' " Enable all functions, which is equivalent to...
"let g:user_emmet_mode='a'   " Enable all functions in all modes.
" To enable just for html/css, use the following two lines of confiugration:
"let g:user_emmet_install_global = 0
"autocmd FileType html,css EmmetInstall

"let g:user_emmet_leader_key='<Tab>' " Default is <C-Y>
"let g:user_emmet_settings = { 'javascript.jsx': { 'extends': 'jsx' } }
Plug 'mattn/vim-gist'

"Plug 'mhartington/vim-typings', { 'for': ['typescript', 'javascript'] } " I don't know that this is really necessary anymore.

Plug 'mhinz/vim-signify'
" Configuration for mhinz/vim-signify


Plug 'mhinz/vim-startify'
Plug 'mhinz/vim-sayonara'
"Plug 'ntpeters/vim-better-whitespace'
" Configuration
" TODO: Setup an autocmd for markdown to ignore trailing whitespace
" TODO: Configure the plugin above
Plug 'ojroques/vim-oscyank', { 'branch': 'main' }
nmap <leader>y <Plug>OSCYank

Plug 'OmniSharp/omnisharp-vim'
Plug 'neovimhaskell/haskell-vim'
if IsWSL()
    let g:OmniSharp_translate_cygwin_wsl = 1
    let g:OmniSharp_selector_ui = ''
endif
Plug 'preservim/vim-markdown', { 'for': 'markdown' }
" Configure the vim_markdown plugin
let g:markdown_fenced_languages = ['html', 'javascript', 'typescript', 'powershell=ps1', 'c#', 'f#', 'css', 'scss', 'less', 'bash=sh', 'conf', 'json', 'toml', 'yaml']
let g:vim_markdown_fenced_languages = ['html', 'javascript', 'typescript', 'powershell=ps1', 'c#', 'f#', 'css', 'scss', 'less', 'bash=sh', 'conf', 'help', 'json', 'toml', 'vim', 'yaml']
let g:markdown_syntax_conceal = 1
let g:vim_markdown_conceal = 1
let g:vim_markdown_conceal_code_blocks = 1
let g:vim_markdown_folding_disabled = 0
let g:vim_markdown_folding_style_pythonic = 1
let g:vim_markdown_toc_autofit = 1
let g:vim_markdown_follow_anchor = 1
let g:vim_markdown_math = 1
let g:vim_markdown_no_default_keyMappings = 0
let g:vim_markdown_frontmatter = 1
let g:vim_markdown_json_frontmatter = 1
let g:vim_markdown_toml_frontmatter = 1
let g:vim_markdown_strikethrough = 1
let g:vim_markdown_auto_insert_bullets = 0
let g:vim_markdown_new_list_item_indent = 0
let g:vim_markdown_no_extensions_in_markdown = 1
let g:vim_markdown_edit_url_in = 'current'  " Supported values: tab, vsplit, hsplit, current
Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'preservim/nerdcommenter'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
"Plug 'Quramy/tsuquyomi', { 'for': ['typescript', 'javascript'] }
"Plug 'Quramy/vim-dtsm'
"Plug 'Quramy/vim-js-pretty-template'
if has('win32')
    Plug 'Shougo/vimproc.vim', { 'branch': 'master', 'do': 'curl -o C:\Users\cshea\.vim\plugged\vimproc.vim\lib\vimproc_win64.dll https://github.com/Shougo/vimproc.vim/releases/latest/download/vimproc_win64.dll' }
elseif IsWSL()
    Plug 'Shougo/vimproc.vim', { 'branch': 'master', 'do': 'curl -o /c/Users/cshea/.vim/plugged/vimproc.vim/lib/vimproc_win64.dll https://github.com/Shougo/vimproc.vim/releases/latest/download/vimproc_win64.dll' }
else
    Plug 'Shougo/vimproc.vim', { 'branch': 'master', 'do': 'make' }
endif

if has('nvim')
    Plug 'Shougo/ddc.vim'
    Plug 'vim-denops/denops.vim'
else
    Plug 'Shougo/ddc.vim'
    Plug 'vim-denops/denops.vim'
    Plug 'roxma/nvim-yarp'
    Plug 'roxma/vim-hug-neovim-rpc'
endif

"Plug 'simeji/winresizer'
"let g:winresizer_gui_enable = 1
"let g:winresizer_start_key = '<C-S>'

Plug 'tpope/vim-characterize'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-dadbod'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-dotenv'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-git'
Plug 'tpope/vim-fugitive'
Plug 'junegunn/gv.vim' " Depends on vim-fugitive above.
Plug 'idanarye/vim-merginal' " Depends on vim-fugitive, and on windows, vimproc.vim
Plug 'christoomey/vim-conflicted' " Depends on vim-fugitive
Plug 'tpope/vim-jdaddy'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-projectionist'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-scriptease'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-speeddating'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-vinegar'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ryanoasis/vim-devicons'
Plug 'enricobacis/vim-airline-clock'

Plug 'ap/vim-css-color'
Plug 'rhysd/committia.vim'
Plug 'lambdalisue/gin.vim'

"let g:airline_theme = 'spaceduck'
let g:airline_theme = 'base16_classic_dark'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
let g:airline#extensions#bookmark#enabled = 1
let g:airline#extensions#bufferline#enabled = 1
let g:airline#extensions#clock#auto = 0
"let g:airline#extensions#clock#format = '%H:%M'
let g:airline#extensions#clock#enabled = 1
let g:airline#extensions#coc#enabled = 1
let g:airline#extensions#coc#show_coc_status = 1
let g:airline#extensions#csv#enabled = 1
let g:airline#extensions#hunks#coc_git = 1
let g:airline#extensions#obsession#enabled = 1
let g:airline#extensions#omnisharp#enabled = 1
let g:airline#extensions#tmuxline#enabled = 0
let g:airline#extensions#whitespace#enabled = 1
" %a = 3-letter day-of-week
" %A = full day-of-week
" %w = number of day of week, 0-6, 0 = Sunday
" %y = two-digit year
" %Y = four-digit year
" %b = 3-lettr month
" %B = full month
" %m = month number, 01..12
" %d = day number, 01..31
" %e = no leading zero day number: 1..31
" %l = no-leading zero hour
" %H = 24-hour hour, 00..23
" %I = 12-hour hour, 01..12
" %M = minutes, 00..59
" %S = seconds, 00..60
" %p = AM/PM indicator
" %Z = TimeZone offset, e.g. +08
" %j = day-of-year, 001..366
" %% = literal '%'
let g:airline#extensions#clock#format = '%a %e %b %Y %H:%M'
let g:airline_powerline_fonts = 1
"let g:airline_left_sep = '\uE0B0'
"let g:airline_right_sep = '\uE0B6'
function! AirlineInit()
  let g:airline_section_z = airline#section#create(["\uE0A1" . '%{line(".")}', ' ', "\uE0A3" . '%{col(".")}', 'clock'])
endfunction
let g:airline_skip_empty_sections = 1
"Plug 'vim-scripts/taglist.vim'
"Plug 'vim-syntastic/syntastic'
"let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_typescriptreact_checkers = ['tsuquyomi']
"let g:syntastic_typescript_checkers = ['tsuquyomi']
"Plug 'vim-test/vim-test'

" TypeScript/JavaScript plugins and their configuration
Plug 'yuezk/vim-js', { 'for': ['javascript','javascriptreact'] }
Plug 'HerringtonDarkholme/yats.vim', { 'for': ['typescript','typescriptreact'] }
Plug 'maxmellon/vim-jsx-pretty', { 'for': ['typescript','typescriptreact'] }

Plug 'bash-lsp/bash-language-server'
Plug 'SirVer/ultisnips'

" COC - Conqueror of Completion
Plug 'neoclide/coc.nvim', { 'branch': 'release' }
" Automatically install the following extensions if they are not already installed:
let g:coc_global_extensions=[
            \ 'coc-css',
            \ 'coc-deno',
            \ 'coc-emoji',
            \ 'coc-eslint',
            \ 'coc-git',
            \ 'coc-html',
            \ 'coc-json',
            \ 'coc-powershell',
            \ 'coc-svg',
            \ 'coc-tag',
            \ 'coc-tsserver',
            \ 'coc-vimlsp',
            \ 'coc-xml',
            \ 'coc-yaml',
            \]
"           \ 'ionide-coc-fsharp'
"           \ 'coc-omni',
"           \ 'coc-snippets',
"           \ 'coc-ultisnips',
"if isdirectory('./node_modules') && isdirectory('./node_modules/prettier')
"    let g:coc_global_extensions += ['coc-prettier']
"endif
"if isdirectory('./node_modules') && isdirectory('./node_modules/eslint')
"    let g:coc_global_extensions += ['coc-eslint']
"endif
Plug 'puremourning/vimspector'
let g:vimspector_enable_mappings='human'
let g:vimspector_base_dir=$HOME."/.vim/plugged/vimspector"

call plug#end()

" note: don't need to set this. per help documentation, as soon as a user .vimrc
" file is found, this is already set! this is not true when the system .vimrc
" file is used, however.
"set nocompatible

" if there's a .vimrc file in the directory in which vim is opened, source it.
set exrc
set showmode
set cmdheight=1
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8
" Set the cursor -- TODO: Lookup more info on this
set guicursor=
set backspace=indent,eol,start
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent smartindent shiftround smarttab
set foldcolumn=5
set foldmethod=indent " fold based on indentation levels
set textwidth=0
" TODO: Perhaps make an autocmd for this so the column is only visible while in INSERT mode...
"set colorcolumn=110
set wrapmargin=2
set relativenumber
set number
set signcolumn=yes
set confirm " confirm destructive operations made on non-saved buffers
set hidden
set lazyredraw
set noerrorbells
set path+=.,**
set title
set wildmenu
set wildmode=list:longest,list:full
set hlsearch
set incsearch
" start scrolling the screen when the cursor reaches 'n' lines from the top/bottom
set scrolloff=8
" When :splitting a window, put the new window below the current window
set splitbelow
" When :vsplitting a window, put the new window to the right of the current window
set splitright
" Set completion mode options (think, intellisense menu)
" My options are:
"  - menuone: Show a menu even for a single match
"  - longest: Only insert the longest common text of the matches. Use <C-L> to enter more text when the
"             popup is shown.
"  - noinsert: Do not insert any text until a selection is actually made
"  - noselect: Do not 'auto-select' a match--user has to explicitly select
"set completeopt=menuone,noinsert,noselect
if (has('patch-8.1.1880'))
    set completeopt=longest,menuone,popuphidden
    set completepopup=highlight:Pmenu,border:off
else
    set completeopt=longest,menuone,preview
    set previewheight = 5
endif
" Enable snippet completion, using the ultisnips plugin
let g:OmniSharp_want_snippet = 1

augroup omnisharp_commands
    autocmd!

    " Show type information automitacally when the cursor stops moving.
    " Note that the type is echoed to the Vim command line, and will overwrite
    " any other messages in this space, including e.g. ALE linting messages.
    autocmd CursorHold *.cs OmniSharpTypeLookup

    " The following commands are contextual, based on the cursor position
    autocmd FileType cs nmap <silent> <buffer> gd <Plug>(omnisharp_go_to_definition)
    autocmd FileType cs nmap <silent> <buffer> <Leader>osfu <Plug>(omnisharp_find_usages)
    autocmd FileType cs nmap <silent> <buffer> <Leader>osfi <Plug>(omnisharp_find_implementations)
    autocmd FileType cs nmap <silent> <buffer> <Leader>ospd <Plug>(omnisharp_preview_definition)
    autocmd FileType cs nmap <silent> <buffer> <Leader>ospi <Plug>(omnisharp_preview_implemenattions)
    autocmd FileType cs nmap <silent> <buffer> <Leader>ost <Plug>(omnisharp_type_lookup)
    autocmd FileType cs nmap <silent> <buffer> <Leader>osd <Plug>(omnishrap_documentation)
    autocmd FileType cs nmap <silent> <buffer> <Leader>osfs <Plug>(omnisharp_find_symbol)
    autocmd FileType cs nmap <silent> <buffer> <Leader>osfx <Plug>(omnisharp_fix_usings)
    autocmd FileType cs nmap <silent> <buffer> <C-\> <Plug>(omnisharp_signature_help)
    autocmd FileType cs imap <silent> <buffer> <C-\> <Plug>(omnisharp_signature_help)

    " Navigate up and down by method/property/field
    autocmd FileType cs nmap <silent> <buffer> [[ <Plug>(omnisharp_navigate_up)
    autocmd FileType cs nmap <silent> <buffer> ]] <Plug>(omnisharp_navigate_down)
    " Find all code errors/warnings for the current solution and populate the quickfix window
    autocmd FileType cs nmap <silent> <buffer> <Leader>osgcc <Plug>(omnisharp_global_code_check)
    " Contextual code actions (uses fzf, vim-clap, CtrlP or unite.vim selector when available)
    autocmd FileType cs nmap <silent> <buffer> <Leader>osca <Plug>(omnisharp_code_actions)
    autocmd FileType cs xmap <silent> <buffer> <Leader>osca <Plug>(omnisharp_code_actions)
    " Repeat the last code action performed (does not use a selector)
    autocmd FileType cs nmap <silent> <buffer> <Leader>os. <Plug>(omnisharp_code_action_repeat)
    autocmd FileType cs xmap <silent> <buffer> <Leader>os. <Plug>(omnisharp_code_action_repeat)

    autocmd FileType cs nmap <silent> <buffer> <Leader>os= <Plug>(omnisharp_code_format)

    autocmd FileType cs nmap <silent> <buffer> <Leader>osnm <Plug>(omnisharp_rename)

    autocmd FileType cs nmap <silent> <buffer> <Leader>osre <Plug>(omnisharp_restart_server)
    autocmd FileType cs nmap <silent> <buffer> <Leader>osst <Plug>(omnisharp_start_server)
    autocmd FileType cs nmap <silent> <buffer> <Leader>ossp <Plug>(omnisharp_stop_server)
augroup END

" Set update time.
" The default is 4s!! Reduce it to at least 100ms
set updatetime=100
" Avoid some 'hit-enter' prompts
set shortmess=filmnrxoOc
" Start diff mode using vertical splits, in addition to the default values
set diffopt+=vertical

" Change the characters that are used for showing whitespace
set listchars="tab:\uF811\uF811,trail:\uB7,nbsp:\u2420,lead:\uB7,space:\uB7,precedes:\u2026,extends:\u2026"


let $RTP=split(&runtimepath, ',')[0]

if (has("termguicolors"))
    set termguicolors
elseif (!has('gui_running'))
    set t_Co=256
endif

if (has('nvim'))
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif

filetype plugin indent on " Indentation rules follow those of plug-ins, then file types.
syntax enable
set background=dark
"colorscheme spaceduck
colorscheme base16-classic-dark

" Improve support for mouse use with mintty
set mouse=a
if has("mouse_sgr")
    set ttymouse=sgr
else
    set ttymouse=xterm2
end

" Override git-for-windows setting clipboard=unnamed causing
" the system clipboard to clobber the default unnamed register
if has("clipboard")
    set clipboard=
endif

" if (has('unnamedplus'))
"     set clipboard=unnamed,unnamedplus
" endif

" Only show line highlighting when in INSERT mode.
augroup fourpastmidnight_vimrc
    autocmd!
    autocmd User * call AirlineInit()
    autocmd BufEnter * setlocal cursorline
    autocmd BufEnter * setlocal colorcolumn=110
    autocmd BufLeave * setlocal nocursorline
    autocmd BufLeave * setlocal colorcolumn=0
    autocmd BufRead,BufNewFile *.[jt]sx? setlocal conceallevel=1
    autocmd BufRead,BufNewFile *.{md,mdx,mdown,mkd,mkdn,markdown,mdwn} setlocal conceallevel=2
    autocmd FileType gitcommit let b:EditorConfig_disable = 1
    autocmd FileType html,css,markdown,sass,scss EmmetInstall
    autocmd FileType javascript setlocal foldmethod=syntax
    autocmd FileType javascript setlocal foldmethod=syntax
    autocmd FileType javascriptreact setlocal foldmethod=syntax
    autocmd FileType scss setlocal iskeyword+=-
    autocmd FileType typescript setlocal foldmethod=syntax
    autocmd FileType typescriptreact setlocal foldmethod=syntax
augroup END

set secure
